# Generated by Django 3.0.14 on 2023-04-16 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0003_auto_20230416_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 16, 12, 40, 17, 711898)),
        ),
        migrations.AlterField(
            model_name='partial',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 16, 12, 40, 17, 711898)),
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 12, 40, 17, 711898)),
        ),
    ]
