# Generated by Django 4.2.7 on 2025-01-07 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0007_alter_code_timestamp_alter_partial_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 1, 7, 15, 38, 8, 981944)),
        ),
        migrations.AlterField(
            model_name='partial',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 1, 7, 15, 38, 8, 982756)),
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 15, 38, 8, 977867)),
        ),
    ]
