# Generated by Django 3.0.14 on 2022-12-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0010_uid_db_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialauth',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersocialauth',
            name='utype',
            field=models.IntegerField(default=0),
        ),
    ]
