# Generated by Django 3.0.14 on 2023-04-02 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0011_auto_20230402_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 2, 11, 22, 22, 522152)),
        ),
        migrations.AlterField(
            model_name='partial',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 2, 11, 22, 22, 522152)),
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 11, 22, 22, 520155)),
        ),
    ]
