# Generated by Django 3.0.14 on 2022-12-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0011_auto_20221204_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialauth',
            name='pic',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
