# Generated by Django 4.2.7 on 2025-01-16 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0013_alter_code_timestamp_alter_partial_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 1, 16, 15, 23, 45, 87888)),
        ),
        migrations.AlterField(
            model_name='partial',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 1, 16, 15, 23, 45, 88550)),
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 15, 23, 45, 85203)),
        ),
    ]
