# Generated by Django 3.0.14 on 2023-04-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0002_auto_20230416_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='profile picture'),
        ),
    ]
