# Generated by Django 3.0.14 on 2022-12-08 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from social_django.models import UserSocialAuth

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_django', '0011_auto_20221204_1528'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursetype_name', models.CharField(max_length=50)),
            ],
        ),
        
    ]
