# Generated by Django 3.0.14 on 2023-03-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0002_auto_20230324_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='banner',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
