# Generated by Django 4.2.7 on 2025-01-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contactno',
            field=models.CharField(default='', max_length=200),
        ),
    ]
