# Generated by Django 3.2.16 on 2022-12-30 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lxpapp', '0002_auto_20221229_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='K8STerminalLearnerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usedvalue', models.PositiveIntegerField(default=0)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='K8STerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.TextField()),
                ('usagevalue', models.PositiveIntegerField(default=0)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k8sterminal_requests_learner', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k8sterminal_requests_trainer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
