# Generated by Django 4.2.7 on 2025-01-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0002_scheduler_userprofile_schedulerstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='type',
            field=models.CharField(choices=[('1', 'Session'), ('2', 'Interview'), ('3', 'Client Requirment'), ('4', 'Lab Call'), ('5', 'Meeting'), ('6', 'Others')], max_length=200, null=True),
        ),
    ]
