# Generated by Django 4.2.7 on 2025-01-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0002_scheduler_userprofile_schedulerstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.IntegerField(default=0)),
                ('urlvalue', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=200)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.chapter')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.subject')),
            ],
            options={
                'ordering': ['subject', 'chapter', 'serial_number'],
            },
        ),
    ]
