# Generated by Django 4.2.7 on 2025-01-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0003_userprofile_contactno'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img/'),
        ),
    ]
