# Generated by Django 3.0.14 on 2023-03-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0003_module_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='banner',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
