# Generated by Django 2.1.3 on 2023-03-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0003_batch_batchcourse_batchlearner_batchtrainer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BatchCourse',
            new_name='BatchCourseSet',
        ),
        migrations.RemoveField(
            model_name='batchcourseset',
            name='course',
        ),
        migrations.AddField(
            model_name='batchcourseset',
            name='courseset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.CourseSet'),
        ),
    ]
