# Generated by Django 3.2.16 on 2022-12-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0003_userpics'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpics',
            name='picpath',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userpics',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
