# Generated by Django 3.2.16 on 2023-01-05 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lxpapp', '0004_cruduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=30)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lxpapp.playlist')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveSessionUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=500)),
                ('correct', models.BooleanField(default=0)),
                ('livequestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lxpapp.livequestion')),
                ('livesession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lxpapp.livesession')),
            ],
        ),
        migrations.AddField(
            model_name='livequestion',
            name='livesession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lxpapp.livesession'),
        ),
    ]
