# Generated by Django 2.1.3 on 2023-03-09 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0004_auto_20230309_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRecordedVDOList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.Batch')),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.Playlist')),
            ],
        ),
        migrations.RemoveField(
            model_name='includeplaylist',
            name='playlist',
        ),
        migrations.DeleteModel(
            name='IncludePlaylist',
        ),
    ]
