# Generated by Django 3.0.14 on 2023-03-25 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lxpapp', '0004_auto_20230324_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerMaterialWatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.CharField(choices=[('PDF', 'PDF'), ('HTML', 'HTML'), ('Video', 'Video'), ('URL', 'URL')], default='PDF', max_length=200)),
                ('urlvalue', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('learner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.Material')),
            ],
        ),
    ]
