# Generated by Django 3.0.14 on 2023-03-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0005_learnermaterialwatched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnermaterialwatched',
            name='description',
        ),
        migrations.RemoveField(
            model_name='learnermaterialwatched',
            name='mtype',
        ),
        migrations.RemoveField(
            model_name='learnermaterialwatched',
            name='urlvalue',
        ),
    ]
