# Generated by Django 3.0.14 on 2023-02-26 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0005_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.Module'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='material',
            name='mtype',
            field=models.CharField(choices=[('PDF', 'PDF'), ('HTML', 'HTML'), ('Video', 'Video'), ('URL', 'URL')], default='PDF', max_length=200),
        ),
        migrations.AlterField(
            model_name='material',
            name='urlvalue',
            field=models.CharField(max_length=200),
        ),
    ]
