# Generated by Django 3.0.14 on 2023-03-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0005_lastuserlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerdetails',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/user/'),
        ),
    ]
