# Generated by Django 4.2.7 on 2025-01-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0006_schedulerstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='eventdetails',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='type',
            field=models.CharField(choices=[('1', 'Lecture'), ('2', 'Event')], max_length=200, null=True),
        ),
    ]
