# Generated by Django 3.0.14 on 2023-04-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0006_learnerdetails_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='session_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
