# Generated by Django 2.1.3 on 2023-03-11 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lxpapp', '0006_exam_mcqquestion_mcqresult_mcqresultdetails_shortquestion_shortresult_shortresultdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='YTExamQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=600)),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('answer', models.CharField(choices=[('1', 'Option1'), ('2', 'Option2'), ('3', 'Option3'), ('4', 'Option4')], max_length=200)),
                ('marks', models.IntegerField(default=1)),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.Playlist')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.Video')),
            ],
        ),
        migrations.CreateModel(
            name='YTExamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField()),
                ('wrong', models.PositiveIntegerField()),
                ('correct', models.PositiveIntegerField()),
                ('timetaken', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ytexamquestion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.YTExamQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='YTExamResultDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.CharField(max_length=200)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.YTExamQuestion')),
                ('ytexamresult', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.YTExamResult')),
            ],
        ),
        migrations.AlterField(
            model_name='exam',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.Batch'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.Exam'),
        ),
        migrations.AlterField(
            model_name='mcqresult',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.Exam'),
        ),
        migrations.AlterField(
            model_name='mcqresult',
            name='learner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mcqresultdetails',
            name='mcqresult',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.McqResult'),
        ),
        migrations.AlterField(
            model_name='mcqresultdetails',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.McqQuestion'),
        ),
        migrations.AlterField(
            model_name='shortquestion',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.Exam'),
        ),
        migrations.AlterField(
            model_name='shortresult',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.Exam'),
        ),
        migrations.AlterField(
            model_name='shortresult',
            name='learner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shortresultdetails',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.ShortQuestion'),
        ),
        migrations.AlterField(
            model_name='shortresultdetails',
            name='shortresult',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapp.ShortResult'),
        ),
    ]
