# Generated by Django 3.0.14 on 2023-01-11 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0007_auto_20230110_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='course',
        ),
        migrations.CreateModel(
            name='BatchCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lxpapp.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lxpapp.Course')),
            ],
        ),
    ]
