# Generated by Django 3.0.14 on 2023-01-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0008_auto_20230111_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
    ]
