# Generated by Django 3.0.14 on 2023-01-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0009_remove_exam_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='fee',
            field=models.IntegerField(default=0),
        ),
    ]
