# Generated by Django 3.0.14 on 2023-01-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0011_learnerfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='fee',
        ),
        migrations.DeleteModel(
            name='LearnerFee',
        ),
    ]
