# Generated by Django 3.0.14 on 2023-01-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0012_auto_20230112_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchlearner',
            name='fee',
            field=models.IntegerField(default=0),
        ),
    ]
