# Generated by Django 3.0.14 on 2022-12-10 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
                ('questiontpye', models.CharField(choices=[('MCQ', 'MCQ'), ('ShortAnswer', 'ShortAnswer')], default='', max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.Course')),
            ],
        ),
    ]
