# Generated by Django 3.0.14 on 2022-12-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmsapp', '0002_auto_20221214_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqresult',
            name='timetaken',
            field=models.CharField(max_length=200),
        ),
    ]
