# Generated by Django 3.0.5 on 2022-11-21 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilmsapp', '0003_auto_20221121_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.Subject'),
            preserve_default=False,
        ),
    ]
