# Generated by Django 3.2.16 on 2022-12-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmsapp', '0003_auto_20221221_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='desciption',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
