# Generated by Django 3.0.14 on 2022-12-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmsapp', '0003_mcqquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquestion',
            name='answer',
            field=models.CharField(choices=[('1', 'Option1'), ('2', 'Option2'), ('3', 'Option3'), ('4', 'Option4')], max_length=200),
        ),
    ]
