# Generated by Django 3.0.14 on 2022-12-16 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ilmsapp', '0003_auto_20221214_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField()),
                ('datecreate', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.Exam')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShortResultDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField()),
                ('answer', models.CharField(max_length=200)),
                ('feedback', models.CharField(default='', max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.ShortQuestion')),
                ('shortresult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.ShortResult')),
            ],
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.Playlist'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.Playlist'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.Playlist'),
        ),
        migrations.AlterField(
            model_name='videolinks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.Playlist'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
