# Generated by Django 3.0.14 on 2022-12-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmsapp', '0004_auto_20221216_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortresult',
            name='timetaken',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
