# Generated by Django 3.2.16 on 2022-12-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilmsapp', '0004_material_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='desciption',
            new_name='description',
        ),
    ]
