# Generated by Django 3.0.14 on 2022-11-27 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilmsapp', '0004_topic_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.Chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.Course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.Subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.Topic')),
            ],
        ),
    ]
