# Generated by Django 3.0.14 on 2022-12-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmsapp', '0005_shortquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=200)),
                ('playlist_id', models.CharField(max_length=200)),
            ],
        ),
    ]
