# Generated by Django 3.0.14 on 2022-12-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmsapp', '0006_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='playlist_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
