# Generated by Django 3.2.16 on 2022-12-18 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ilmsapp', '0006_auto_20221218_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.PositiveIntegerField(default=0)),
                ('TopicName', models.CharField(max_length=600)),
                ('VideoTime', models.CharField(max_length=600)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=200)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoTopicCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicCovered', models.PositiveIntegerField(default=0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoToUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoWatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.video')),
            ],
        ),
        migrations.CreateModel(
            name='WaringMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usermailid', models.TextField()),
                ('mailed', models.TextField()),
                ('totvideo', models.IntegerField(default=0)),
                ('watched', models.IntegerField(default=0)),
                ('watchedperc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pending', models.IntegerField(default=0)),
                ('datetimestamp', models.DateTimeField()),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='VideoLinks',
        ),
    ]
