# Generated by Django 3.0.14 on 2022-12-10 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilmsapp', '0007_subject_playlist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrNo', models.PositiveIntegerField()),
                ('Url', models.CharField(max_length=200)),
                ('video_id', models.CharField(max_length=200)),
                ('TopicCovered', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.Chapter')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmsapp.Subject')),
            ],
        ),
    ]
