# Generated by Django 5.1.5 on 2025-01-27 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchrecordedvdolist',
            name='Subject',
        ),
        migrations.AlterField(
            model_name='batchcourse',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_courses', to='lxpapiapp.batch'),
        ),
        migrations.AlterField(
            model_name='batchlearner',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_learners', to='lxpapiapp.batch'),
        ),
        migrations.AlterField(
            model_name='batchrecordedvdolist',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_videos', to='lxpapiapp.batch'),
        ),
        migrations.AlterField(
            model_name='batchtrainer',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_trainers', to='lxpapiapp.batch'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchrecordedvdolist',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lxpapiapp.subject'),
        ),
    ]
